### ISSUE TITLE
QXcbConnection: Could not connect to display

### ISSUE THREAD

**Issue by AmazingDreams** [cloudify/sPDF#40]
I'm using a Gitlab runner for CI. When I run the tests to generate a PDF I run into the error:

`QXcbConnection: Could not connect to display`

This causes the output stream to be empty, that is to say, this test fails:

```scala
result.toByteArray.size must not be 0
```
Dockerfile:

```sh
FROM java:8

RUN apt-get update && apt-get -y install apt-transport-https \
    && echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list \
    && apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823 \
    && apt-get update \
    && apt-get -y install sbt \

    # Cleanup
    && apt-get clean \
    && rm -rf /var/lib/apt/lists \
```

Build job:

```yml
test:
  image: <private>/docker:sbt
  stage: test
  services:
  - mysql:5.6
  variables:
    MYSQL_DATABASE: "<private>"
    MYSQL_ROOT_PASSWORD: "<private>"
  script:
  - apt-get update
  - apt-get install -y --no-install-recommends wkhtmltopdf
  - sbt clean coverage test coverageReport
  artifacts:
    expire_in: 1d
    paths:
    - target/scala-2.11/scoverage-report/
```

Please let me know if you need more information.
